"""Demand pack catalog data (spec §4.4, §12) — pure data, no DB writes. The
catalog seed framework (owned elsewhere) consumes `BLOCKS`/`METRICS` and
writes the rows.
"""

from typing import Any

OWNER = "demand-eng"
DOMAIN = "demand"
GIT_SHA = "dev"

BLOCKS: list[dict[str, Any]] = [
    {
        "name": "panel_builder",
        "kind": "data",
        "owner": OWNER,
        "domain": DOMAIN,
        "tags": ["demand", "elasticity", "panel"],
        "version": "1.0",
        "git_sha": GIT_SHA,
        "image_ref": None,
        "entrypoint": "packs.demand.blocks.panel_builder:run",
        "params_schema": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string",
                    "not": {"enum": ["gozero", "haleon"]},
                    "description": "The synthetic demo pipeline's own brand — never one with a real "
                    "ds-models run (those use elasticity_real instead).",
                },
                "platform": {"type": "string"},
                "window": {
                    "type": "object",
                    "properties": {
                        "from": {"type": "string", "description": "YYYY-MM"},
                        "to": {"type": "string", "description": "YYYY-MM"},
                    },
                    "required": ["from", "to"],
                },
            },
            "required": ["brand", "platform", "window"],
        },
        "cost_class": "seconds",
        "sideeffect_class": "compute",
        "when_to_use": "First node of a DML elasticity or promo pipeline; builds the sku x week x platform panel.",
        "when_not_to_use": "When a panel for the same brand/platform/window was already built upstream in this plan.",
        "status": "active",
        "consumes": [],
        "produces": [{"contract": "dml_panel@v1", "port": "panel"}],
        "gates": [],
    },
    {
        "name": "elasticity_dml",
        "kind": "model",
        "owner": OWNER,
        "domain": DOMAIN,
        "tags": ["demand", "elasticity", "dml"],
        "version": "1.0",
        "git_sha": GIT_SHA,
        "image_ref": None,
        "entrypoint": "packs.demand.blocks.elasticity_dml:run",
        "params_schema": {
            "type": "object",
            "properties": {
                "force_positive_elasticities": {
                    "type": "boolean",
                    "default": False,
                    "description": "Demo/test knob only — forces a broken (positive) surface.",
                },
            },
            "required": [],
        },
        "cost_class": "seconds",
        "sideeffect_class": "compute",
        "when_to_use": "Estimate per-SKU price elasticity from a dml_panel@v1 handle.",
        "when_not_to_use": "When an elasticity surface already exists for the same panel and is still fresh.",
        "status": "active",
        "consumes": [{"contract": "dml_panel@v1", "port": "panel"}],
        "produces": [{"contract": "elasticity_surface@v1", "port": "surface"}],
        "gates": [{"check_suite": "post_model_checks", "when": "post", "policy": "block"}],
    },
    {
        "name": "elasticity_real",
        "kind": "model",
        "owner": OWNER,
        "domain": DOMAIN,
        "tags": ["demand", "elasticity", "ds-models", "real"],
        "version": "1.0",
        "git_sha": GIT_SHA,
        "image_ref": None,
        "entrypoint": "packs.demand.blocks.elasticity_real:run",
        "params_schema": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string",
                    "enum": ["gozero", "haleon"],
                    "description": "A brand with a real, already-fitted ds-models elasticity run.",
                },
                "platform": {"type": "string"},
            },
            "required": ["brand"],
        },
        "cost_class": "seconds",
        "sideeffect_class": "read",
        "when_to_use": "Real per-SKU price elasticity for a brand ds-models has actually modeled (gozero, "
        "haleon) — the shipped DML/Bayesian-shrinkage/causal-forest/PSM-DiD-calibrated numbers. Prefer this "
        "over elasticity_dml whenever the ask names one of these real brands; no panel_builder needed, the "
        "model already ran inside ds-models.",
        "when_not_to_use": "The synthetic 'demo' brand, or any brand with no shipped ds-models run — use "
        "elasticity_dml (panel_builder -> elasticity_dml) for those instead.",
        "status": "active",
        "consumes": [],
        "produces": [{"contract": "elasticity_surface@v1", "port": "surface"}],
        "gates": [{"check_suite": "post_model_checks", "when": "post", "policy": "block"}],
    },
    {
        "name": "post_model_checks",
        "kind": "validation",
        "owner": OWNER,
        "domain": DOMAIN,
        "tags": ["demand", "validation", "elasticity"],
        "version": "1.0",
        "git_sha": GIT_SHA,
        "image_ref": None,
        "entrypoint": "packs.demand.blocks.post_model_checks:run",
        "params_schema": {"type": "object", "properties": {}},
        "cost_class": "instant",
        "sideeffect_class": "read",
        "when_to_use": "Mandatory post-gate on model-kind blocks producing an elasticity_surface@v1.",
        "when_not_to_use": "Never skip — a model node without this gate is invalid by construction.",
        "status": "active",
        "consumes": [{"contract": "elasticity_surface@v1", "port": "surface"}],
        "produces": [{"contract": "validation_verdicts@v1", "port": "verdicts"}],
        "gates": [],
    },
    {
        "name": "scenario_projection",
        "kind": "scenario",
        "owner": OWNER,
        "domain": DOMAIN,
        "tags": ["demand", "scenario", "pricing"],
        "version": "1.0",
        "git_sha": GIT_SHA,
        "image_ref": None,
        "entrypoint": "packs.demand.blocks.scenario_projection:run",
        "params_schema": {
            "type": "object",
            "properties": {
                "platform": {"type": "string"},
                "week": {"type": "string", "description": "YYYY-MM-DD"},
                "price_delta_pct": {"type": "number", "description": "e.g. -0.1 for a 10% price cut"},
            },
            "required": ["platform", "week", "price_delta_pct"],
        },
        "cost_class": "instant",
        "sideeffect_class": "compute",
        "when_to_use": "Counterfactual price-change asks over an existing elasticity surface.",
        "when_not_to_use": "When a constrained/optimized allocation is wanted instead of a single scenario — use promo_optimizer.",
        "status": "active",
        "consumes": [{"contract": "elasticity_surface@v1", "port": "surface"}],
        "produces": [{"contract": "promo_plan@v1", "port": "plan"}],
        "gates": [],
    },
    {
        "name": "promo_optimizer",
        "kind": "optimizer",
        "owner": OWNER,
        "domain": DOMAIN,
        "tags": ["demand", "optimizer", "pricing"],
        "version": "1.0",
        "git_sha": GIT_SHA,
        "image_ref": None,
        "entrypoint": "packs.demand.blocks.promo_optimizer:run",
        "params_schema": {
            "type": "object",
            "properties": {
                "platform": {"type": "string"},
                "week": {"type": "string", "description": "YYYY-MM-DD"},
                "budget": {"type": "number"},
                "max_discount_pct": {"type": "number", "default": 0.3},
            },
            "required": ["platform", "week", "budget"],
        },
        "cost_class": "seconds",
        "sideeffect_class": "compute",
        "when_to_use": "Recommendation asks: greedily allocate a discount budget across SKUs by elasticity.",
        "when_not_to_use": "Single what-if price change asks — use scenario_projection instead.",
        "status": "active",
        "consumes": [{"contract": "elasticity_surface@v1", "port": "surface"}],
        "produces": [{"contract": "promo_plan@v1", "port": "plan"}],
        "gates": [],
    },
    {
        "name": "runs_history",
        "kind": "query",
        "owner": OWNER,
        "domain": DOMAIN,
        "tags": ["demand", "control-plane", "ops"],
        "version": "1.0",
        "git_sha": GIT_SHA,
        "image_ref": None,
        "entrypoint": "packs.demand.blocks.runs_history:run",
        "params_schema": {
            "type": "object",
            "properties": {"limit": {"type": "integer", "default": 10}},
        },
        "cost_class": "instant",
        "sideeffect_class": "read",
        "when_to_use": "Ops/status asks: recent runs for the requesting tenant.",
        "when_not_to_use": "Cross-tenant run history — always tenant-scoped.",
        "status": "active",
        "consumes": [],
        "produces": [],
        "gates": [],
    },
    {
        "name": "promote_model",
        "kind": "promotion",
        "owner": OWNER,
        "domain": DOMAIN,
        "tags": ["demand", "promotion", "elasticity"],
        "version": "1.0",
        "git_sha": GIT_SHA,
        "image_ref": None,
        "entrypoint": "packs.demand.blocks.promote_model:run",
        "params_schema": {
            "type": "object",
            "properties": {
                # Constrained (not a free-form string): brand/platform flow into a
                # filesystem path in the adapter (packs.demand.blocks.promote_model),
                # so the contract itself is the first line of defense against path
                # traversal (spec §4.3 "the contract is the whole truth").
                "brand": {"type": "string", "pattern": "^[A-Za-z0-9_-]+$", "maxLength": 64},
                "platform": {"type": "string", "pattern": "^[A-Za-z0-9_-]+$", "maxLength": 64},
                "alias": {"type": "string", "enum": ["champion", "candidate"], "default": "champion"},
            },
            "required": ["brand", "platform"],
        },
        "cost_class": "instant",
        "sideeffect_class": "mutate_state",
        "when_to_use": "Promote an elasticity surface to the champion/candidate registry alias for a brand/"
        "platform — always requires a named approver distinct from the requester (spec §8 two-person rule).",
        "when_not_to_use": "Read-only elasticity asks with no intent to change what's live — use elasticity_dml "
        "or scenario_projection instead.",
        "status": "active",
        "consumes": [{"contract": "elasticity_surface@v1", "port": "surface"}],
        "produces": [{"contract": "report_ref@v1", "port": "report"}],
        "gates": [],
    },
    {
        "name": "loss_making_skus",
        "kind": "metric",
        "owner": OWNER,
        "domain": DOMAIN,
        "tags": ["demand", "margin", "kpi"],
        "version": "1.0",
        "git_sha": GIT_SHA,
        "image_ref": None,
        "entrypoint": "packs.demand.blocks.loss_making_skus:run",
        "params_schema": {
            "type": "object",
            "properties": {
                "brand": {"type": "string"},
                "platform": {"type": "string"},
                "margin_threshold": {"type": "number", "default": 0.0},
            },
            "required": ["brand", "platform"],
        },
        "cost_class": "instant",
        "sideeffect_class": "read",
        "when_to_use": "Analytic asks: 'how many SKUs made losses' style KPI lookups.",
        "when_not_to_use": "When a real margin mart exists for the tenant — this is a demo stand-in.",
        "status": "active",
        "consumes": [],
        "produces": [],
        "gates": [],
    },
]

METRICS: list[dict[str, Any]] = []
